function createButton() {
          const myButton = document.createElement('button');
            myButton.classList.add('my-button');
            myButton.textContent = 'MY BUTTON';
            myButton.style.position = 'fixed';
            myButton.style.bottom = '20px';
            myButton.style.left = '100px';
            myButton.style.bottom = '40px';
            myButton.style.zIndex = '1000';
            myButton.style.padding = '10px 20px';
            myButton.style.backgroundColor = '#007bff';
            myButton.style.color = '#fff';
            myButton.style.border = 'none';
            myButton.style.borderRadius = '55px';
            myButton.style.cursor = 'pointer';
            document.body.appendChild(myButton);
            const popupContainer = document.createElement('div');
            popupContainer.classList.add('chat-popup');
            popupContainer.style.position = 'fixed';
            popupContainer.style.bottom = '70px';
            popupContainer.style.left = '100px';
            popupContainer.style.zIndex = '1000';
            popupContainer.style.backgroundColor = '#fff';
            popupContainer.style.border = '1px solid #ccc';
            popupContainer.style.borderRadius = '5px';
            popupContainer.style.boxShadow = '0 4px 8px rgba(0, 0, 0, 0.2)';
            popupContainer.style.padding = '10px';
            popupContainer.style.display = 'none';
            const chatOptions = ['Facebook', 'Instagram', 'X', 'T', 'Email'];
            chatOptions.forEach(option => {
                const optionButton = document.createElement('button');
                optionButton.textContent = option;
                optionButton.style.display = 'block';
                optionButton.style.margin = '5px 0';
                optionButton.style.padding = '10px';
                optionButton.style.width = '100%';
                optionButton.style.backgroundColor = '#f1f1f1';
                optionButton.style.border = 'none';
                optionButton.style.borderRadius = '3px';
                optionButton.style.cursor = 'pointer';
                optionButton.addEventListener('click', () => {
                    alert(`Redirecting to ${option}`);
                });
                popupContainer.appendChild(optionButton);
            });
            document.body.appendChild(popupContainer);
            myButton.addEventListener('click', () => {
                popupContainer.style.display = popupContainer.style.display === 'none' ? 'block' : 'none';
            });
        };
  createButton();
